# FILE: docker-compose.yaml
# PURPOSE: To simulate a production build on your local machine.
# This file uses the production Dockerfiles to create production-ready images.

services:
  # Build the production image for the API
  relayr-api:
    container_name: relayr-api-localbuild
    image: relayr-api-localbuild
    build:
      context: ./relayr-api
      dockerfile: Dockerfile # Uses the final production Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"

  # Build the production image for the UI
  relayr-ui:
    container_name: relayr-ui-localbuild
    image: relayr-ui-localbuild
    build:
      context: ./relayr-ui
      dockerfile: Dockerfile # Uses the final production Dockerfile
      args:
        # This value will be baked into the static files
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    platform: linux/amd64
    ports:
      # The production UI image serves on port 80 (inside the container)
      - "3000:80"
    depends_on:
      - relayr-api
