services:
  relayr-api:
    build:
      context: ./relayr-api
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: relayr-api
    image: ghcr.io/rifuki/relayr/relayr-api:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  relayr-ui:
    depends_on:
      - relayr-api
    build:
      context: ./relayr-ui
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    platform: linux/amd64
    container_name: relayr-ui
    image: ghcr.io/rifuki/relayr/relayr-ui:latest
    ports:
      - "3000:80"
    restart: unless-stopped
