name: Rust CI

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build
        working-directory: relayr-api
        run: cargo build --verbose --release
      - name: Clippy
        working-directory: relayr-api
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Tests
        working-directory: relayr-api
        run: cargo test --verbose
